import 'package:cloud_firestore/cloud_firestore.dart';

class TaskModel {
  final String id;
  final String title;
  final String description;
  final String? contactId;
  final String channel;
  final String template;
  final String status; // pending, ready_to_send, sent, done
  final bool autoGenerated;
  final String sourceInsightId;
  final Timestamp? createdAt;
  final Timestamp? dueAt;
  final Timestamp? remindAt;
  final String assignedTo;

  TaskModel({
    required this.id,
    required this.title,
    required this.description,
    this.contactId,
    this.channel = 'email',
    this.template = '',
    this.status = 'pending',
    this.autoGenerated = false,
    this.sourceInsightId = '',
    this.createdAt,
    this.dueAt,
    this.remindAt,
    required this.assignedTo,
  });

  factory TaskModel.fromFirestore(DocumentSnapshot doc) {
    final d = doc.data() as Map<String, dynamic>? ?? {};
    return TaskModel(
      id: doc.id,
      title: d['title'] ?? '',
      description: d['description'] ?? '',
      contactId: d['contactId'],
      channel: d['channel'] ?? 'email',
      template: d['template'] ?? '',
      status: d['status'] ?? 'pending',
      autoGenerated: d['autoGenerated'] ?? false,
      sourceInsightId: d['sourceInsightId'] ?? '',
      createdAt: d['createdAt'],
      dueAt: d['dueAt'],
      remindAt: d['remindAt'],
      assignedTo: d['assignedTo'] ?? '',
    );
  }

  Map<String, dynamic> toMapForCreate() {
    return {
      'title': title,
      'description': description,
      'contactId': contactId,
      'channel': channel,
      'template': template,
      'status': status,
      'autoGenerated': autoGenerated,
      'sourceInsightId': sourceInsightId,
      'createdAt': FieldValue.serverTimestamp(),
      'dueAt': dueAt ?? FieldValue.serverTimestamp(),
      'remindAt': remindAt ?? FieldValue.serverTimestamp(),
      'assignedTo': assignedTo,
    };
  }
}