import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../providers/task_provider.dart';
import '../../data/models/task_model.dart';
import 'task_detail_screen.dart';

class TasksListScreen extends StatelessWidget {
  const TasksListScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final prov = context.watch<TaskProvider>();
    final tasks = prov.tasks;

    return Scaffold(
      appBar: AppBar(title: const Text('Tasks & Reminders')),
      body: tasks.isEmpty
          ? const Center(child: Text('No tasks yet'))
          : ListView.separated(
              itemCount: tasks.length,
              separatorBuilder: (_, __) => const Divider(),
              itemBuilder: (ctx, i) {
                final TaskModel t = tasks[i];
                return ListTile(
                  leading: Icon(t.autoGenerated ? Icons.auto_mode : Icons.task),
                  title: Text(t.title),
                  subtitle: Text('${t.channel} • ${t.status}'),
                  trailing: Text(t.dueAt != null ? _formatTs(t.dueAt) : ''),
                  onTap: () => Navigator.of(ctx).push(MaterialPageRoute(builder: (_) => TaskDetailScreen(task: t))),
                );
              },
            ),
    );
  }

  static String _formatTs(ts) {
    if (ts == null) return '';
    try {
      final dt = (ts as dynamic).toDate();
      return '${dt.year}-${dt.month.toString().padLeft(2,'0')}-${dt.day.toString().padLeft(2,'0')}';
    } catch (e) {
      return '';
    }
  }
}